os: windows
language: shell
install: true
branches:
  only:
    - master
cache:
  directories:
    - java8
    - gradle
before_script:
  - choco install jdk8 -params 'installdir=c:\\java8'
  - export PATH=$PATH:"/c/java8/bin"
  - choco install gradle --version 5.0 -params 'installdir=c:\\gradle'
  - export PATH=$PATH:"/c/gradle/bin"
script:
  - gradle generateGrammarSource
  - gradle shadowJar
  - gradle createExe
deploy:
  provider: releases
  api_key:
    secure: IJ1wUcsm5qmHuKrfNeYeacS8rLhf6y+Mzudrb5bXb2U/HlqPSEcrUM/zgy6Qnh+gpnbNiMeFYiJaqxIFT1iONgw62dlhw0XAkjfRR2Ra5ycAvX88mqS5wY9v7cUeCrS3yMhch3vNCjtBPT+LszaT89P8ElEmPU8KoGhtqqOpsjnGp/ZcwsuAPFKn3/pP79CB3wejS4hoRKSDsWQHEtwWttoMp/4V1eAruYE6wl88hsL8sggL7cMpybUKS6KdAVW7ZNzVObaX5FLzV6LzFum0qMfFr00oIqK+hDuvrxZK70qRjkcY5qI6J5VpGilV0gn8sU2PXClZDlvqQiJHkuP8EdKQYsCwR6xOIumD1SnQFR8aX8Vpk5pqrkOSqCdjNJIhBehooZRx9+PjHeK/8MxSiVCVee1MogVFjJonpCYCgmslAElP+WNsE8s2kpIYN31/eKOmoD5IkRgy8QfetLmX+24xUGiAeL1408rE9xgyhiqIith7DmHUAwkiWIERq4PD71nVCELHywR/T9aZrby50W/qyW0RUSqms621o5a/FdCnRSDIWC0yBFy/b5tu5OxBauqO/DVnH3QijTikRN/B1phT7rmJzsj1h/CIqU92PnaS0GLpsXioWZIDuccTOJc5qptuyIOfr5kv4OSqVtcgbaPfUFfTyBQBhTepIoGetjk=
  file:
    - 'C:\\Users\\travis\\build\\DeflatedPickle\\Rawky\\build\\libs\\Rawky.jar'
    - 'C:\\Users\\travis\\build\\DeflatedPickle\\Rawky\\build\\libs\\Rawky.exe'
  on:
    repo: DeflatedPickle/Rawky
  draft: true
  skip_cleanup: true